### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by HCLarsen** [amberframework/liquid.cr#82]
There have been a lot of changes made to this library since the last release was made in 2021. We should look at making a new release, but there's a question of if these changes constitute a major or minor release version. 

@hugopl @crimson-knight, thoughts?

**Comment by hugopl** [comment]
My mantra usually is _Release early, release often_.

IMO this must be released as a major, because it's basically a rewrite and may have a lot of behavior change due to fixed bugs that maybe someone is using as a feature.

**Comment by HCLarsen** [comment]
I'm in agreement. The other question is documentation. We probably should have something to indicate what changes in terms of behaviour. At the very least, a short blurb. Is anyone up for writing that? I'd offer, but I don't know what these changes are.

**Comment by hugopl** [comment]
I used to known the changes... but it's a long time 😅 ... I remember that I was using [Golden Liquid](https://github.com/jg-rp/golden-liquid) test suite and now this shard pass in a lot of tests however still 384 tests failing.

Related files:
spec/integration/golden_liquid.yaml
spec/integration/golden_liquid.pending
spec/integration/integration_spec.cr

last released version fails in a large amount of tests with this suite, I don't know if it's worth to try to run `spec/integration/integration_spec.cr` with old version to check how many tests pass there then compare with the current code and use this information in the release notes.

Unfortunately I can't promise to write documentation due to my free time constraints 😢, but I can try to help with information 😁

**Comment by HCLarsen** [comment]
In terms of documentation of classes and methods, I'm happy to write those as I use the shard and discover how everything works. It's more "release notes" that I'm currently thinking of. I guess we can ask ourselves if it's really important, given how small this shard's audience is.

**Comment by hugopl** [comment]
Nice to see 1.0.0rc, I believe we can close this, right?

**Comment by HCLarsen** [comment]
Yeah, I think we can.
